# Generated by Django 4.1.3 on 2022-11-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingmart", "0037_remove_adeemaform_1_prof_pic"),
    ]

    operations = [
        migrations.DeleteModel(name="adeemaform_1",),
        migrations.RenameField(
            model_name="student_data", old_name="Email", new_name="desc",
        ),
        migrations.RenameField(
            model_name="student_data", old_name="Father_name", new_name="email",
        ),
        migrations.RenameField(
            model_name="student_data", old_name="Password", new_name="num",
        ),
        migrations.RenameField(
            model_name="student_data", old_name="User_name", new_name="password",
        ),
        migrations.RemoveField(model_name="student_data", name="About_user",),
        migrations.RemoveField(model_name="student_data", name="prof_pic",),
        migrations.AddField(
            model_name="student_data",
            name="images",
            field=models.ImageField(default="", upload_to="image"),
        ),
    ]
